blank_issues_enabled: false
contact_links:
  - name: strands-compose Discussions
    url: https://github.com/strands-compose/sdk-python/discussions
    about: Please ask and answer questions here
  - name: strands-compose Documentation
    url: https://github.com/strands-compose/sdk-python/tree/main/docs
    about: Visit the documentation for help
